#!/bin/sh

set -e

function print_help {
	echo "
xtype  - types weird characters into the current X window

xtype CHAR_NAME

CHAR_NAME:
	¨  - uml | umlaut
	ä  - auml | aumlaut
	Ä  - Auml | Aumlaut
	ö  - ouml | oumlaut
	Ö  - Ouml | Oumlaut
	ü  - uuml | uumlaut
	Ü  - Uuml | Uumlaut
	ÿ  - yuml | yumlaut
	Ÿ  - Yuml | Yumlaut
	ß  - eszett | eszet | ss
	ẞ  - Eszett | Eszet | SS
	€  - eur | euro
	₽  - rub | rur
	£  - gbp | pound
	¢  - cent
	α  - alpha
	β  - beta
	γ  - gamma
	Γ  - Gamma
	δ  - delta
	Δ  - Delta
	ε  - epsilon
	Ε  - Epsilon
	ζ  - zeta
	Ζ  - Zeta
	η  - eta
	Η  - Eta
	θ  - theta
	Θ  - Theta
	ι  - iota
	Ι  - Iota
	κ  - kappa
	Κ  - Kappa
	λ  - lambda
	Λ  - Lambda
	μ  - mu
	Μ  - Mu
	ν  - nu
	Ν  - Nu
	ν  - xi
	Ν  - Xi
	ο  - omicron
	Ο  - Omicron
	π  - pi
	Π  - Pi
	ρ  - rho
	Ρ  - Rho
	ς  - sigma
	Σ  - Sigma
	τ  - tau
	Τ  - Tau
	υ  - upsilon
	Υ  - Upsilon
	φ  - phi
	Φ  - Phi
	χ  - chi
	Χ  - Chi
	ψ  - psi
	Ψ  - Psi
	ω  - omega
	Ω  - Omega
	ℵ  - alef
	æ  - ae | aelig
	♭  - flat
	♯  - sharp
	✓  - check
	✗  - cross
	µ  - micro
	—  - mdash
	–  - ndash
	‐  - hyphen | hyph
	¬  - not
	   - nbsp
	±  - +-
	≤  - <= | geq
	≥  - >= | leq
	≠  - != | neq
	≈  - almost | =~ | ~= | asymp
	≶  - lg
	∀  - forall
	∃  - exists | exist | there_exists
	∿  - sine | acd
	∫  - int | integral
	∬  - Int | dint
	∭  - iiint | tint
	⌀  - diameter
	°  - deg | dergee
	∅  - empty
	∈  - isin
	∉  - notin
	⊂  - sub
	⊃  - sup
	⌈  - lceil
	⌉  - rceil
	⌊  - lfloor
	⌋  - rfloor
	∑  - sum
	∗  - lowast
	∝  - prop | proportional_to
	∟  - angrt
	∠  - ang
	∡  - angmsd
	∥  - parallel
	∦  - npar
	∧  - and
	∨  - or
	∩  - cap | intersection
	∪  - cup | union
	∏  - prod
	√  - sqrt
	♲  - recycle
	∞  - inf | infinity
	↑  - up
	↓  - down
	™  - tm
	§  - section
	§  - division
	…  - ellipsis | hellip
	′  - prime
	″  - Prime | dprime
	‴  - tprime
	‵  - bprime
	⁗  - qprime
	ƒ  - fnof | func
	‽  - interrobang
	¶  - pilcrow | para
	⁋  - rpilcrow
	•  - bullet | bull
	⁃  - hybull | hyphen_bullet
	¦  - brvbar
	⁰  - sup0
	¹  - sup1
	²  - sup2
	³  - sup3
	⁴  - sup4
	⁵  - sup5
	⁶  - sup6
	⁷  - sup7
	⁸  - sup8
	⁹  - sup9
"
}

out=""
case $1 in
	help | --help)
		print_help;
		exit 0;
		;;
	uml | umlaut)
		out="¨"
		;;
	auml | aumlaut)
		out="ä"
		;;
	Auml | Aumlaut)
		out="Ä"
		;;
	ouml | oumlaut)
		out="ö"
		;;
	Ouml | Oumlaut)
		out="Ö"
		;;
	uuml | uumlaut)
		out="ü"
		;;
	Uuml | Uumlaut)
		out="Ü"
		;;
	yuml)
		out="ÿ"
		;;
	Yuml)
		out="Ÿ"
		;;
	eszett | ss)
		out="ß"
		;;
	Eszett | SS)
		out="ẞ"
		;;
	eur | euro)
		out="€"
		;;
	rub | rur)
		out="₽"
		;;
	gbp | pound)
		out="£"
		;;
	cent)
		out="¢"
		;;
	alpha)
		out="α"
		;;
	beta)
		out="β"
		;;
	gamma)
		out="γ"
		;;
	Gamma)
		out="Γ"
		;;
	delta)
		out="δ"
		;;
	Delta)
		out="Δ"
		;;
	epsilon)
		out="ε"
		;;
	Epsilon)
		out="Ε"
		;;
	zeta)
		out="ζ"
		;;
	Zeta)
		out="Ζ"
		;;
	eta)
		out="η"
		;;
	Eta)
		out="Η"
		;;
	theta)
		out="θ"
		;;
	Theta)
		out="Θ"
		;;
	iota)
		out="ι"
		;;
	Iota)
		out="Ι"
		;;
	kappa)
		out="κ"
		;;
	Kappa)
		out="Κ"
		;;
	lambda)
		out="λ"
		;;
	Lambda)
		out="Λ"
		;;
	mu)
		out="μ"
		;;
	Mu)
		out="Μ"
		;;
	nu)
		out="ν"
		;;
	Nu)
		out="Ν"
		;;
	xi)
		out="ν"
		;;
	Xi)
		out="Ν"
		;;
	omicron)
		out="ο"
		;;
	Omicron)
		out="Ο"
		;;
	pi)
		out="π"
		;;
	Pi)
		out="Π"
		;;
	rho)
		out="ρ"
		;;
	Rho)
		out="Ρ"
		;;
	sigma)
		out="ς"
		;;
	Sigma)
		out="Σ"
		;;
	tau)
		out="τ"
		;;
	Tau)
		out="Τ"
		;;
	upsilon)
		out="υ"
		;;
	Upsilon)
		out="Υ"
		;;
	phi)
		out="φ"
		;;
	Phi)
		out="Φ"
		;;
	chi)
		out="χ"
		;;
	Chi)
		out="Χ"
		;;
	psi)
		out="ψ"
		;;
	Psi)
		out="Ψ"
		;;
	omega)
		out="ω"
		;;
	Omega)
		out="Ω"
		;;
	alef)
		out="ℵ"
		;;
	ae | aelig)
		out="æ"
		;;
	flat)
		out="♭"
		;;
	sharp)
		out="♯"
		;;
	check)
		out="✓"
		;;
	cross)
		out="✗"
		;;
	micro)
		out="µ"
		;;
	mdash)
		out="—"
		;;
	ndash)
		out="–"
		;;
	hyphen | hyph)
		out="‐"
		;;
	not)
		out="¬"
		;;
	nbsp)
		out=" "
		;;
	"+-")
		out="±"
		;;
	"<=" | geq)
		out="≤"
		;;
	">=" | leq)
		out="≥"
		;;
	!= | neq)
		out="≠"
		;;
	almost | =~ | ~= | asymp)
		out="≈"
		;;
	lg)
		out="≶"
		;;
	forall)
		out="∀"
		;;
	exists | exist | there_exists)
		out="∃"
		;;
	sine | acd)
		out="∿"
		;;
	int | integral)
		out="∫"
		;;
	Int | dint)
		out="∬"
		;;
	iiint | tint)
		out="∭"
		;;
	diameter)
		out="⌀"
		;;
	deg | dergee)
		out="°"
		;;
	empty)
		out="∅"
		;;
	isin)
		out="∈"
		;;
	notin)
		out="∉"
		;;
	sub)
		out="⊂"
		;;
	sup)
		out="⊃"
		;;
	lceil)
		out="⌈"
		;;
	rceil)
		out="⌉"
		;;
	lfloor)
		out="⌊"
		;;
	rfloor)
		out="⌋"
		;;
	sum)
		out="∑"
		;;
	lowast)
		out="∗"
		;;
	prop | proportional_to)
		out="∝"
		;;
	angrt)
		out="∟"
		;;
	ang)
		out="∠"
		;;
	angmsd)
		out="∡"
		;;
	parallel)
		out="∥"
		;;
	npar)
		out="∦"
		;;
	and)
		out="∧"
		;;
	or)
		out="∨"
		;;
	cap | intersection)
		out="∩"
		;;
	cup | union)
		out="∪"
		;;
	prod)
		out="∏"
		;;
	sqrt)
		out="√"
		;;
	recycle)
		out="♲"
		;;
	inf | infinity)
		out="∞"
		;;
	up)
		out="↑"
		;;
	down)
		out="↓"
		;;
	tm)
		out="™"
		;;
	section)
		out="§"
		;;
	division)
		out="§"
		;;
	ellipsis | hellip)
		out="…"
		;;
	prime)
		out="′"
		;;
	Prime | dprime)
		out="″"
		;;
	tprime)
		out="‴"
		;;
	bprime)
		out="‵"
		;;
	qprime)
		out="⁗"
		;;
	fnof | func)
		out="ƒ"
		;;
	interrobang)
		out="‽"
		;;
	pilcrow | para)
		out="¶"
		;;
	rpilcrow)
		out="⁋"
		;;
	bullet | bull)
		out="•"
		;;
	hybull | hyphen_bullet)
		out="⁃"
		;;
	brvbar)
		out="¦"
		;;
	sup0)
		out="⁰"
		;;
	sup1)
		out="¹"
		;;
	sup2)
		out="²"
		;;
	sup3)
		out="³"
		;;
	sup4)
		out="⁴"
		;;
	sup5)
		out="⁵"
		;;
	sup6)
		out="⁶"
		;;
	sup7)
		out="⁷"
		;;
	sup8)
		out="⁸"
		;;
	sup9)
		out="⁹"
		;;
esac

if [ "$out" == "" ]; then 
	echo "invalid argument $1
use \"help\" for list of characters and their names"
	exit 1
fi

# echo "$out"

xdotool type "$out"
